project_id = "nhdawwtkixcgwcfdbzot"

[functions.generate-workout]
verify_jwt = false

[functions.generate-overload]
verify_jwt = false

[functions.generate-macrocycle]
enabled = true
verify_jwt = true
import_map = "./functions/generate-macrocycle/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-macrocycle/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-macrocycle/*.html" ]
